pluginManagement {
    plugins {
        id 'org.jetbrains.kotlin.jvm' version '2.3.10'
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}
rootProject.name = "livecommerce"

include(
        "app",
        "common",
        "member",
        "commerce",
        "broadcast",
        "order",
        "payment",
        "settlement"
)