plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':common')
    implementation project(':member')
    implementation project(':commerce')
    implementation project(':broadcast')
    implementation project(':order')
    implementation project(':payment')
    implementation project(':settlement')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-amqp'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.flywaydb:flyway-mysql'
    runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}
